// vue-composition-test/src/components/UserInfo.vue
<script setup>
import { ref } from "vue";

const user = ref({ name: "Jan", age: 25 });

const updateAge = () => {
  user.value.age++;
};
</script>

<template>
  <div>
    <h2>Dane użytkownika</h2>
    <p>Imię: {{ user.name }}</p>
    <p>Wiek: {{ user.age }}</p>
    <button @click="updateAge">Zwiększ wiek</button>
  </div>
</template>

// react-test-hooks-components/src/components/UserInfo.jsx
import { useState } from "react";

function UserInfo() {
  const [user, setUser] = useState({ name: "Jan", age: 25 });

  return (
    <div>
      <h2>Dane użytkownika</h2>
      <p>Imię: {user.name}</p>
      <p>Wiek: {user.age}</p>
      <button onClick={() => setUser((prev) => ({ ...prev, age: prev.age + 1 }))}>
        Zwiększ wiek
      </button>
    </div>
  );
}

export default UserInfo;
