// next_nest_nuxt/complex/nuxt-complex-app/pages/about.vue
<template>
  <div>
    <Head>
      <Title>O Nas - Nuxt Demo</Title>
    </Head>
    <h1>O Nas</h1>
    <p>Jesteśmy firmą demonstracyjną pokazującą możliwości Nuxt 3.</p>
    <p>Naszym celem jest tworzenie świetnych aplikacji webowych z Vue.</p>
  </div>
</template>

<script setup lang="ts"></script>

// next_nest_nuxt/complex/next-complex-app-router/app/about/page.tsx
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'O Nas', // To zostanie połączone z szablonem z layout.tsx
  description: 'Dowiedz się więcej o naszej firmie demonstracyjnej.',
};

export default function AboutPage() {
  return (
    <>
      <h1>O Nas</h1>
      <p>Jesteśmy firmą demonstracyjną pokazującą możliwości Next.js App Router.</p>
      <p>Naszym celem jest tworzenie świetnych aplikacji webowych, które są szybkie i przyjazne SEO.</p>
    </>
  );
}
