// test-hooks/src/components/Posts.jsx
import { useState, useEffect } from "react";

function Posts() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/posts?_limit=5")
      .then((res) => res.json())
      .then((data) => setPosts(data));
  }, []);

  return (
    <div>
      <h2>Posty z API</h2>
      {posts.length === 0 ? (
        <p>Ładowanie postów...</p>
      ) : (
        <ul>
          {posts.map((post) => (
            <li key={post.id}>{post.title}</li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default Posts;

// components/vue-composition-test/src/components/Posts.vue
<script setup>
import { ref, onMounted } from "vue";

const posts = ref([]);

onMounted(async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=5");
  posts.value = await res.json();
});
</script>

<template>
  <div>
    <h2>📩 Posty z API</h2>
    <ul v-if="posts.length > 0">
      <li v-for="post in posts" :key="post.id">{{ post.title }}</li>
    </ul>
    <p v-else>Ładowanie postów...</p>
  </div>
</template>
