// components/angular-test-components/src/app/components/posts/posts.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common'; // ✅ Importujemy CommonModule

@Component({
  selector: 'app-posts',
  templateUrl: './posts.component.html',
  styleUrls: ['./posts.component.css'],
  imports: [CommonModule] // ✅ To pozwala używać *ngFor
})
export class PostsComponent implements OnInit {
  posts: any[] = [];

  ngOnInit() {
    fetch('https://jsonplaceholder.typicode.com/posts?_limit=5')
      .then(response => response.json())
      .then(data => this.posts = data);
  }
}

// test-hooks/src/components/Posts.jsx
import { useState, useEffect } from "react";

function Posts() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/posts?_limit=5")
      .then((res) => res.json())
      .then((data) => setPosts(data));
  }, []);

  return (
    <div>
      <h2>Posty z API</h2>
      {posts.length === 0 ? (
        <p>Ładowanie postów...</p>
      ) : (
        <ul>
          {posts.map((post) => (
            <li key={post.id}>{post.title}</li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default Posts;
