// components/vue-composition-test/src/components/TaskList.vue
<script setup>
import { ref } from "vue";

const tasks = ref(["Kup mleko", "Zrób obiad"]);

const addTask = () => {
  tasks.value.push(`Nowe zadanie ${tasks.value.length + 1}`);
};
</script>

<template>
  <div>
    <h2>Lista zadań</h2>
    <ul>
      <li v-for="(task, index) in tasks" :key="index">{{ task }}</li>
    </ul>
    <button @click="addTask">Dodaj zadanie</button>
  </div>
</template>

// react-test-hooks/src/components/TaskList.jsx
import { useState } from "react";

function TaskList() {
  const [tasks, setTasks] = useState(["Kup mleko", "Zrób obiad"]);

  const addTask = () => {
    setTasks((prev) => [...prev, `Nowe zadanie ${prev.length + 1}`]);
  };

  return (
    <div>
      <h2>Lista zadań</h2>
      <ul>
        {tasks.map((task, index) => (
          <li key={index}>{task}</li>
        ))}
      </ul>
      <button onClick={addTask}>Dodaj zadanie</button>
    </div>
  );
}

export default TaskList;
