// components/vue-composition-test/src/components/TaskList.vue
<script setup>
import { ref } from "vue";

const tasks = ref(["Kup mleko", "Zrób obiad"]);

const addTask = () => {
  tasks.value.push(`Nowe zadanie ${tasks.value.length + 1}`);
};
</script>

<template>
  <div>
    <h2>Lista zadań</h2>
    <ul>
      <li v-for="(task, index) in tasks" :key="index">{{ task }}</li>
    </ul>
    <button @click="addTask">Dodaj zadanie</button>
  </div>
</template>

// components/angular-test-components/src/app/components/task-list/task-list.component.ts
import { Component } from '@angular/core';

import { CommonModule } from '@angular/common'; // ✅ Importujemy CommonModule

@Component({
  selector: 'app-task-list',
  standalone: true, // ✅ Jeśli używasz Angular 15+
  templateUrl: './task-list.component.html',
  styleUrls: ['./task-list.component.css'],
  imports: [CommonModule] // ✅ To pozwala używać *ngFor
})

export class TaskListComponent {
  tasks: string[] = ['Kup mleko', 'Zrób obiad'];

  addTask() {
    this.tasks.push(`Nowe zadanie ${this.tasks.length + 1}`);
  }
}
